### ISSUE TITLE
Emote autocompletion inside the emote

### ISSUE THREAD

**Issue by Daisenki** [flex3r/DankChat#102]
The autocompletion for emotes works only when you start with the first letters of the emote, it doesn't work inside the emote name. I give you an example:

"dan" and you get "DansGame"
"gam" give me nothing

The emote "locoleThink", I need to type "loc" and pick it in the list, it would be great if I could type "thi" or "think" to get "locoleThink"

**Comment by flex3r** [comment]
Looks like this not possible and out of scope for the current component I'm using for autocompletion (https://developer.android.com/reference/android/widget/MultiAutoCompleteTextView).  
Maybe possible in the future if I switch to another solution.
