### ISSUE TITLE
Realize of DankChat on iOS 

### ISSUE THREAD

**Issue by splinter1998** [flex3r/DankChat#111]
Guys I really love your app but now I’ve switched to iPhone running on iOS 14.3 I want to tell u if it’s possible to have the app on the (App Store ) thank u so much if it’s happening guys

**Comment by flex3r** [comment]
No, DankChat is written natively for Android and I don't have any experience in iOS development unfortunately. Additionally, Apple is much stricter with third-party apps and apps can't keep running in the background like DankChat can on Android.
