### ISSUE TITLE
create Arabic Translate

### ISSUE THREAD

**Issue by splinter1998** [flex3r/DankChat#112]
hello idk if it's in the right section cause i created an **_arabic translation_** for the app and i wanted to show it to u 

[strings-AR.txt](https://github.com/flex3r/DankChat/files/5756811/strings-AR.txt)

**Comment by flex3r** [comment]
Support of that was added recently already in #109. You can compare your translations with the existing ones if you want and let me know of any improvements. 👍

**Comment by flex3r** [comment]
Will close this for know, lmk if you have any suggestions for the translation
