### ISSUE TITLE
Add a way to follow a user in the app

### ISSUE THREAD

**Issue by zneix** [flex3r/DankChat#113]
**What should be added?**
A way to follow a user in DankChat:tm: It can use Helix's [`Create User Follows`](https://dev.twitch.tv/docs/api/reference#create-user-follows) I thought about couple examples of a potential implementation:
1. A label in channel's context menu. This could also make use of [`Get Users Follows`](https://dev.twitch.tv/docs/api/reference#get-users-follows) to make this label "dynamic" (display either "Follow" or "Unfollow" based on whether you're already following the user or not).
2. A custom command (similar to how it is done in Chatterino:tm:)

**Why should it be added?**
A simple example can be seen below:
https://cdn.zneix.eu/1UZgmdv.png
![if you read this VI VON](https://cdn.zneix.eu/1UZgmdv.png)

**Comment by flex3r** [comment]
Implemented in e0e2a47acd2d57f9db909ce2cb06d1c4473491c2
