### ISSUE TITLE
timeouts are two times displayed

### ISSUE THREAD

**Issue by Daisenki** [flex3r/DankChat#114]
not sure if this is a bug, but commands like timeouts are 2x displayed, perma bans and other commands only once, it's not a big deal, just a little bit annoying, would be nice if you could fix it with a future update pls 

![Screenshot_20210108-002520~(2)](https://user-images.githubusercontent.com/22057956/103956699-5eceb680-5149-11eb-8a41-8b26b45fc4f6.jpg)

**Comment by flex3r** [comment]
That's because the bot is actually sending 2 timeouts. Other chat clients probably have timeout stacking which DankChat doesn't have at the moment.
