### ISSUE TITLE
If emote exists on both BTTV and FFZ, both are rendered in the message

### ISSUE THREAD

**Issue by b-ggs** [flex3r/DankChat#115]
In #hasanabi, `haHAA` exists as both a Channel FFZ Emote and a Global BTTV Emote.

![image](https://user-images.githubusercontent.com/6130147/106097855-ffc1f780-6172-11eb-9a26-31a2e41c001d.png)

Both emotes are rendered in place of `haHAA` as shown below in DankChat:

![image](https://user-images.githubusercontent.com/6130147/106097015-8d9ce300-6171-11eb-9219-96498b37faf1.png)

The behavior is different between chat clients / extensions:
- In Chatterino 2.2.3-beta2, the emote rendered is the Channel FFZ Emote
- In FFZ for Chrome with BTTV through FFZ:AP, the emote rendered is the Channel FFZ Emote
- In BTTV for Chrome with FFZ emotes, the emote rendered is the Global BTTV Emote

I'm not sure whether FFZ or BTTV should take precedence (or maybe Channel vs Global), but I think at the least only one emote should be rendered

**Comment by flex3r** [comment]
Good catch, will fix this soon!
