### ISSUE TITLE
Disconnected Error

### ISSUE THREAD

**Issue by replaisment** [flex3r/DankChat#118]
Text input field remains in "Disconnected" state until the app is restarted, even if there is an internet connection. Incoming messages still load, but the "Disconnected" doesn't go away.

**Comment by flex3r** [comment]
Will look into it, until then there's also a "Reconnect" option in the option menu at the top

**Comment by replaisment** [comment]
> Will look into it, until then there's also a "Reconnect" option in the option menu at the top

So the bug happened again today and there was no "Reconnect" option. It stayed disconnected, yet I was able to receive messages, but not send any. Had to do a full restart of the app.

**Comment by flex3r** [comment]
The option is in the three dots menu->More->Reconnect

**Comment by flex3r** [comment]
Closing this for now, as there have been many changes since then. Feel free to open if the issue still exists
