### ISSUE TITLE
Add badges visibility options

### ISSUE THREAD

**Issue by replaisment** [flex3r/DankChat#120]
Would love for the ability to turn off seeing certain badges and/or all badges ala FrankerFaceZ's badges visibility options. A simple toggle for all badges would be appreciated as well. 

![image](https://user-images.githubusercontent.com/77034555/108438245-b7db4100-7203-11eb-8a94-f3460abd8ee8.png)

**Comment by flex3r** [comment]
I implemented Chatterinos version of this in 6d2630f9d8940480737bd31ba16e5fe74b23907e. Grouping the badges in their main categories makes more sense than adding a toggle for each individual badge, at least for mobile imo.
