### ISSUE TITLE
If an emote with the same name exists as a Channel FFZ Emote and Shared BTTV Emote, both are rendered 

### ISSUE THREAD

**Issue by b-ggs** [flex3r/DankChat#125]
Like #115, this is very unlikely to happen, but just thought I'd submit an issue for it.

In `#datadave`, `KEKW` exists as a Channel FFZ Emote and a Shared BTTV Emote. Both are rendered below in DankChat 2.5.3 Play Store:

![image](https://user-images.githubusercontent.com/6130147/111574614-ca876c80-87e7-11eb-89e4-c7b76853f851.png)

In Chatterino 2.2.3-beta2, only the Channel FFZ Emote is rendered:

![image](https://user-images.githubusercontent.com/6130147/111574711-f9054780-87e7-11eb-8f53-0daaf5072662.png)

**Comment by b-ggs** [comment]
I just realized that the commit that fixes #115 hasn't been released yet. Apologies. Please feel free to close this issue if this has been covered by 7baed93e60e8fd0bb610ccf917a52dcfba6e7c61.

**Comment by flex3r** [comment]
No worries, and yeah I should build a new release 😄
