### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by jspricke** [flex3r/DankChat#127]
Hi, your last releases fail to build on F-Droid:
```
/home/vagrant/build/com.flxrs.dankchat/app/src/main/kotlin/com/flxrs/dankchat/preferences/DeveloperSettingsFragment.kt:16: Error: Upgrade Fragment version to at least 1.3.0. [InvalidFragmentVersionForActivityResult]
    private val requestCheckTTSData = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
                                      ^
```
https://monitor.f-droid.org/builds/log/com.flxrs.dankchat/181

Can you have a look?

**Comment by flex3r** [comment]
Thanks, for the build log, I actually saw the build failure in the wiki but there weren't any logs attached to it. 
Also weird that local builds seem to work fine..

**Comment by flex3r** [comment]
Seems like it was an issue on google's side: https://stackoverflow.com/a/66740530

**Comment by flex3r** [comment]
I'll also add a `app:lintVitalRelease` step to my ci so any build failures like this can be avoided in the future
