### ISSUE TITLE
Sort channels

### ISSUE THREAD

**Issue by PeterPedro** [flex3r/DankChat#134]
Hello is there any way to sort the channel list? I accidentally removed my favorite channel because the Remove Channel option is right under Hide Toolbar, so I added the channel back but now it is the last one in the list so I'd like to know if there's a way to move it back to the first place without having to delete every single channel and start over again? I know I'll probably click Remove Channel by accident again...

**Comment by flex3r** [comment]
This feature is actually in beta already! You can manage/reorder channels and removing a channel actually asks you for confirmation now.
If you used play store to install DankChat, you can opt-in to the beta there too
