### ISSUE TITLE
About the new viewer info panel / mention

### ISSUE THREAD

**Issue by Osahashi** [flex3r/DankChat#142]
Please add an setting to switch on and off the new user info panel or maybe find another way, because it completely destroys the fast mention possibility. 
One feature I really liked about DankChat was that you can easily touch on the username to copy it for a mention, it offers a fast way to answers questions or anything someone say to you. Now it is not possible anymore because you add the user info panel, don't get me wrong, I like the panel, but I don't want to lose the fast reply feature.
Another way I think would be maybe to set the panel to touch hold, to replace the copy feature of a message.

**Comment by flex3r** [comment]
How about by default, short pressing will open the panel and long pressing will fast-mention, but I add a setting where you can flip the behavior?

**Comment by Osahashi** [comment]
Sounds good! Thanks :)
