### ISSUE TITLE
Support 7TV emotes

### ISSUE THREAD

**Issue by DAmNRelentless** [flex3r/DankChat#143]
There is a new "third party thing" called 7TV which provides more emotes. They also support gifs and wide gifs. It would be really nice to see those in DankChat as well.

There was also a custom chatterino fork created for that: https://github.com/SevenTV/chatterino7

The website: https://7tv.app/

**Comment by flex3r** [comment]
The site has no TOS or privacy policy, seems to have no emote moderation and no public api documentation. I've already seen multiple racist emotes on there and this could easily get me banned from the Play Store.

So no, I won't be adding support for it until they improve in these points and are less sketchy.

**Comment by DAmNRelentless** [comment]
A different branch which is not pushed to playstore updates where we can manually install it via .apk maybe?

**Comment by flex3r** [comment]
I don't plan on implementing and maintaining something like that since I want to work on stuff I am actually interested in. 
Of course someone else can create a fork similiar to the Chatterino one.

**Comment by Mm2PL** [comment]
Now this website actually has ToS and a privacy policy but they very generic. https://7tv.app/legal/privacy https://7tv.app/legal/tos and there are now API docs https://github.com/SevenTV/ServerGo/blob/master/docs/rest-api.md

**Comment by flex3r** [comment]
Soon ™️
