### ISSUE TITLE
"Take picture" and "Record video" not working in beta

### ISSUE THREAD

**Issue by cWve** [flex3r/DankChat#159]
**Description**
When trying to click on either `Upload media --> Take picture` or `Upload media --> Record video` camera doesn't open, nothing happens at all.
It works properly on latest stable release (2.6.1)

**Device**
Pixel 4A Android 11

**Version**
DankChat Beta 2.7.13

**Comment by flex3r** [comment]
Can't reproduce on latest beta (2.7.14). Can you provide additional debug information? For example what camera apps you have installed and which one is set as default.
DankChat just launches an intent with the `MediaStore.ACTION_IMAGE_CAPTURE` or `MediaStore.ACTION_VIDEO_CAPTURE` action which lets you pick any installed camera app that can handle those. This is nothing special and should definitely work.

**Comment by cWve** [comment]
I believe the only app I have installed that acts as a camera is Google Camera itself.
Aside from the pre-installed google apps, I have these apps that use the camera in some way or another:
- Whatsapp/Telegram/Instagram/Discord/Reddit  (camera works inside all of these apps)
- Photoscan (camera also works)
- I also have installed [IP Webcam](https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en_US&gl=US) which allows me to broadcast my camera (like DroidCam does). I've uninstalled it just in case but the problem still occurs.

I've tried clearing cache and data, problem still persists. If you can think of something else, I'll be glad to help

**Comment by cWve** [comment]
Using git-bisect I've found that the problem arises in c27fff0

Using an AVD in Android Studio, I can reproduce the issue with an emulation of a Pixel 3a with Android 11 (API 30), as shown in the video. However, using a Pixel 3a with Android 10 (API 29), the issue does not occur.

https://user-images.githubusercontent.com/16579297/123731026-ab44b480-d897-11eb-8b92-e67a6afd8bbc.mp4

What the video shows is the same as I experience on my real phone

**Comment by flex3r** [comment]
Are there any errors in logcat after starting the actions?

**Comment by cWve** [comment]
No, no logs show up there after clicking on any of the two buttons

**Comment by cWve** [comment]
I did some digging on the web and found projects with similar problems, it seems to be a problem with package visibility in API 30, and it seems to happen in at least Google phones.
https://github.com/OJ7/cordova-plugin-camera/pull/1
https://developer.android.com/training/package-visibility
https://developer.android.com/training/package-visibility/use-cases

I managed to find a workaround using [this solution](https://stackoverflow.com/a/64204646/8953927)
cWve/DankChat@2a15dd9d

**Comment by flex3r** [comment]
Nice find, I will add this workaround then 👍
