### ISSUE TITLE
Newly Added Static Emotes (emotes_v2) missing from suggestions and emote menu

### ISSUE THREAD

**Issue by schmosby** [flex3r/DankChat#161]
Hello! I'm noticing that newly added static emotes from streamers aren't appearing in the emote menu or as suggestions. They appear fine in chat when typed manually. It appears that twitch has changed their ID format from a int to a string in the emotes_v2(hash) format shortly after they released the new emotes API.

An example of this can be seen on the twitchemotes.com site for the sthHeart icon for the streamer SethDrums.

[https://twitchemotes.com/channels/147155277](https://twitchemotes.com/channels/147155277)

![Screenshot 2021-06-29 3 35 16 PM](https://user-images.githubusercontent.com/5651207/123856962-b62b3380-d8ef-11eb-9574-d9b282ca0364.png)

The sthHeart emote was re-uploaded recently and the id now has a string of emotesv2_5ad88d692486461faaa2592d8e5b3464

Screenshots of it missing from suggestions and menu:
![Screenshot_20210629-152143](https://user-images.githubusercontent.com/5651207/123856164-c1ca2a80-d8ee-11eb-8d77-dd563c43b9aa.png)
![Screenshot_20210629-151121](https://user-images.githubusercontent.com/5651207/123856169-c262c100-d8ee-11eb-8904-9b570c7a4f52.png)

Currently on 2.7.14 version of dankchat (beta in play store)

Thank you!

**Comment by flex3r** [comment]
Unfortunately Twitch doesn't provide us a proper way to get these new emotes, we can fetch some of them through the irc USERSTATE messages but as you can tell not all of them are included. 
I don't think there is a proper way to fix this until Twitch provides us an updated endpoint to get a User's Emotes
