### ISSUE TITLE
[Suggestion] A way of seeing channel point redeems in chat

### ISSUE THREAD

**Issue by Joro1144** [flex3r/DankChat#164]
Chatterino has this feature into their application ([Link of them adding it](https://github.com/Chatterino/chatterino2/pull/1809))  is there a way this can be implemented?

**Comment by flex3r** [comment]
Yep, as soon as pubsub is integrated into dankchat this can be added

**Comment by flex3r** [comment]
Added in 22dae030b0c1fbe5308b4044b5cad61b2e9dbf5e

**Comment by rodrigograca31** [comment]
This feature has a bug....
The redeems only show if you are connected to the chat at the moment.

The chat history feature doesnt show the redeems.
**Would it be possible to start including them?** 

Currently I have a bot that mentions me and tells me what was redeemed. that way it is in the chat history.

**Comment by flex3r** [comment]
Unfortunately point redemptions are not tied to the chat connection but rather use another twitch system called PubSub. 
We don't have a way to get past redemptions for this system so they are only available while dankchat is running and connected to it.

**Comment by flex3r** [comment]
That's unfortunately not as simple, as this system requires authentication from the users themselves. So a dedicated service that stores redemptions and provides a history is simply not possible.

**Comment by rodrigograca31** [comment]
all good no worries! 👍🏻
I will use my current solution.
thanks!
