### ISSUE TITLE
App keeps disconnecting and reconnecting on my new phone 

### ISSUE THREAD

**Issue by AWildLink** [flex3r/DankChat#176]
On my old phone this used to happen one every few minutes but now it happens every few seconds, and makes the app completely unusable (old phone was a galaxy a31 and new phone is OnePlus Nord 2)

**Comment by flex3r** [comment]
Are the disconnects happening only in the background or also while the app is active?
Make sure to disable any batter savers or restrictions that might be active and add DankChat to a whitelist if possible.

**Comment by AWildLink** [comment]
I allowed battery usage in the background for dankchat and it works now, thanks a lot
