### ISSUE TITLE
Links after text can't be opened up - Android 6.0.1

### ISSUE THREAD

**Issue by KararTY** [flex3r/DankChat#183]
Doesn't open up when tapped on:
![Screenshot_20211007-102336](https://user-images.githubusercontent.com/13697809/136348470-84dd8aa8-735a-49ab-8bec-72855b5163a4.jpg)

Does open when tapped on:
![Screenshot_20211007-102532](https://user-images.githubusercontent.com/13697809/136348171-7ecc36a6-a0c3-4f8d-9051-97928d39730c.jpg)

Android 6.0.1 - SM-N920C Rooted Default ROM

**Comment by cWve** [comment]
I have this same issue on my huawei P10 with Android 7
DankChat 3.6.22
When the link text is wrapped, something weird happens, only a section of the link becomes clickable:


https://user-images.githubusercontent.com/16579297/235640005-ea9df2ef-6a82-4566-ba59-43e0ba40300d.mp4

**Comment by flex3r** [comment]
I guess I'll close this since I will likely drop support for Android 6 in the near future
