### ISSUE TITLE
Switching Chat Too Sensitive 

### ISSUE THREAD

**Issue by gitguest54** [flex3r/DankChat#215]
Swiping left or right when having multiple channels is extremely sensitive. It takes little effort to activate the switch. I sometimes switch to the next chat on accident just by swiping up to view the current chat.

**Comment by flex3r** [comment]
That is unfortunately the default behavior of the Android component I am using and there's no exposed setting to change this sensitivity. 
I might be able to adjust it in a hacky way though, since this is also something that botheres me.
