### ISSUE TITLE
[Bug] White screen appears after leaving the keyboard in horizontal mode

### ISSUE THREAD

**Issue by cWve** [flex3r/DankChat#216]
Device: Pixel 4a
Version: 3.0.5

[Video](https://i.cwve.xyz/OlympicToryVideo.mp4) (I can't attach cause it's too big)

How to reproduce:
1. Turn your phone to enter "horizontal mode"
2. Open the keyboard
3. Leave the keyboard

**Comment by flex3r** [comment]
Can reproduce, will look into it

**Comment by flex3r** [comment]
Well I'm dumb: https://github.com/flex3r/DankChat/blob/master/app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt#L1059
