### ISSUE TITLE
Stream viewer is restarted when changing phone orientation

### ISSUE THREAD

**Issue by cWve** [flex3r/DankChat#218]
Version: 3.0.6
Phone: Pixel 4a

Steps to reproduce:
1. Open a stream
2. Turn your phone horizontally
3. The stream will reload again

**Comment by flex3r** [comment]
I already spent quite some time trying to fix this, unfortunately the WebView cannot retain or restore its state by itself. I tried some stuff to restore it manually but apart from remembering it's page url or simple attributes via the bundle, no luck. 
The only thing that I can think of that could work, is manually creating an instance of the view, removing it from the parent before an orientation change and manually attaching it again. - I am not going into that hell though, no way. 
Going to mark this with wontfix for now.
