### ISSUE TITLE
Virtual Keyboard switches focus to the first Channel on list.

### ISSUE THREAD

**Issue by MotorHorse** [flex3r/DankChat#223]
Not sure if this issue has already been brought up, but I searched and couldn't find any similarly described issue listed. My apologies if this is a repost. It's a bit difficult to explain, so please forgive the wall of text:

I've noticed that when a stream is toggled (and only when a stream is toggled... plain text chat doesn't have this issue as far as I've seen), the selected channel switches to the first channel on my list when switching focus to the keyboard (triggered by clicking " Start Chatting", of course).  Which forces me to re-select the channel I wish to post my message that I just typed (assuming, of course, that it wasn't the first channel on my list that I wished to post on) before hitting enter or send. This has led to many posts in the wrong chat, as you can imagine, prior to noticing this issue.

**Comment by flex3r** [comment]
Hm, I can't seem to reproduce this issue. What phone and android version are you using?

**Comment by flex3r** [comment]
Fixed in 27e5ff065c670ea546bf6c8a402c708d4e282cbf
