### ISSUE TITLE
Give more detailed error messages when data loading fails

### ISSUE THREAD

**Issue by flex3r** [flex3r/DankChat#224]
For example which service or data loading part failed

**Comment by Catbugsuga** [comment]
![Screenshot_20220125-034041_DankChat](https://user-images.githubusercontent.com/98388450/150951871-ad981d24-1a8d-4b1b-8895-fd1492c00aaa.jpg)
Do you mean this?

**Comment by flex3r** [comment]
Yeah, right now I am just showing the generic exception that caused the data loading failure. Instead I could show specific error messages, for example in this case that the message history service is unavailable
