### ISSUE TITLE
DankChat opening Twitch Chat

### ISSUE THREAD

**Issue by Blitszy** [flex3r/DankChat#226]
So when I try to chat in DankChat multitasked with Twitch, it opens the Twitch chat when attempting to type. It automatically disappears when you remove your keyboard. Very strange.

**Comment by flex3r** [comment]
If you are talking about the Twitch app "stealing" focus, there is nothing I can do about that. The Twitch app always had weird behaviour in multi window mode unfortunately.
If you are talking about something else I need more context, some screenshots or a video would help.

**Comment by flex3r** [comment]
Closing this as I haven't received an answer. Feel free to open it again if you can provide the additional information
