### ISSUE TITLE
Recent emotes issue

### ISSUE THREAD

**Issue by Forza22** [flex3r/DankChat#231]
Can you remove emotes getting bumped to the front after just one use. It makes it extremely annoying when u wanna post the same emote more than once. Instead of recents just make it favorites

**Comment by flex3r** [comment]
I guess this is a side effect of getting the recent emote usages sorted by time. I could instead sort them by name inside the menu. Would that be fine?

**Comment by Forza22** [comment]
Sorry in advance if I sounded demanding. This was more frustrating than I expected. Anything that would keep them from moving would be appreciated
