### ISSUE TITLE
Multiple users timeouts are showed as single user timeout

### ISSUE THREAD

**Issue by LiphiTC** [flex3r/DankChat#233]
![image](https://user-images.githubusercontent.com/48130941/154819574-e406d095-996f-4919-92c2-4e18dc5dd736.png)
![image](https://user-images.githubusercontent.com/48130941/154819656-c3260588-3f58-4324-94e2-35400c5a1ce0.png)

**Comment by flex3r** [comment]
This is intended. Timeouts towards the same user in a 5s period are now stacked to reduce the amount of spam messages. Similar behaviour can be seen in Chatterino as well.

**Comment by flex3r** [comment]
Nvm, I can't read

**Comment by flex3r** [comment]
Seems to be an oversight on my side, needs an additional user id check here: https://github.com/flex3r/DankChat/blob/master/app/src/main/kotlin/com/flxrs/dankchat/utils/extensions/ChatItemExtensions.kt#L19
