### ISSUE TITLE
Enable case sensitive mentions option 

### ISSUE THREAD

**Issue by adityakalra16** [flex3r/DankChat#235]
So currently when you mention a username through typing the letters manually and using the emote picker/user picker, the mention auto uses lower case for the full username, instead of retaining the original capitalisation of the name. 
Would be cool so that we can mention it the way their username is. 

Thanks.

**Comment by zneix** [comment]
wouldn't a regex be technically a solution here? While it isn't the best option and characters like dot, question mark, etc. would need to be escaped, it gets the job done:
![case-sensitive highlight with regex](https://cdn.zneix.eu/AU9lYcx.jpg)

**Comment by flex3r** [comment]
Unfortunately the current api used for retrieving chatters returns all usernames in lower case, e.g. https://tmi.twitch.tv/group/user/flex3rs/chatters
However I have added an improvement here #332 that will override these suggestions with the correct case if the user has typed recently
