### ISSUE TITLE
Problems connecting the account

### ISSUE THREAD

**Issue by zezofelipe** [flex3r/DankChat#236]
Unable to login. The email says the account has been connected, but the app keeps asking to sign in. maybe a oauth2 authorization could be the solution (?)

**Comment by flex3r** [comment]
I am using oauth2 authorization, so not sure what the issue could be. The flow I am using is: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-implicit-code-flow  
Can you try clearing your app data & cache? Also what email are you referring to?

**Comment by zezofelipe** [comment]
Thanks for replying, I tried again after formatting the Android, and re-enabled Twitch two-factor authorization, and it worked.
