### ISSUE TITLE
Fix data usage

### ISSUE THREAD

**Issue by nvalis** [flex3r/DankChat#24]
I am not sure what causes it, but for a simple text chat app DankChat seems to have a pretty high data consumption (in the order of MB/min).

My guess is that the emotes are refetched for every new message. But I am not sure.

**Comment by flex3r** [comment]
Emotes are cached so while data usage at start can be quite high it should settle down afterwards. How long did you have the app open and how much data did it use?

**Comment by flex3r** [comment]
Closing this for now
