### ISSUE TITLE
Add setting for a unencrypted connection

### ISSUE THREAD

**Issue by fossdd** [flex3r/DankChat#242]
Hey,

i've got a plan on my mobile phone where i have free internet but slow.

It would be nice to have a setting where DankChat uses a unencrypted connection to the twitch irc server. So even on my super slow internet my phone still can send and receive messages.

A additional feature, maybe a seperat issue, would be caching some images for some time. So like sub badges which does not change often are cached for a week or so.

Thank you

**Comment by flex3r** [comment]
I might add a developer setting for your first request. 
Regarding the 2nd point, the [image library](https://github.com/coil-kt/coil) I use already heavily caches every request where possible. I don't think I will add a separate caching mechanism in the near future as I don't see the benefit in it. Emotes or badges are really small in size anyways and are only loaded once per app start.

**Comment by fossdd** [comment]
I'm fine with the first point. If i'm able to get and send messages, I don't need to immediately load all images. Thank you

**Comment by flex3r** [comment]
I just checked if this is even possible and unfortunately Android does not allow cleartext communication by default. I could set a special flag in DankChat's manifest to allow it, but it is against the Google Play Store policies to send sensitive user data over unsecured connections anyways: https://support.google.com/googleplay/android-developer/answer/10144311?visit_id=637882302803415459-420211588&rd=1
Even the chat connection contains sensitive user data as I have to send your username and authentication token during the initial connection process. After thinking about it, a setting to disable HTTPS just feels wrong, even if the policies would allow it. 
I'm closing this issue therefore.
