### ISSUE TITLE
Enhancement: Add option to block Bot's mention

### ISSUE THREAD

**Issue by Civon** [flex3r/DankChat#243]
Mostly bots mention you when you are currently focusing on & interact with them. Then, the mention notification popping up becomes a bit annoying. 

## Suggestion
In Notifications & Mentions, add a sub-setting when "Show mention notifications" Enable.
Named: "Block Bots mention notification" 
With selection list: 
(default bot)
- Nightbot
- StreamElements
- Moobot
(custom bot)
- optional

❤️

**Comment by flex3r** [comment]
I have decided against adding such a default bot ignore list. 
However, with #332 you will be able to more easily block any amount of users.
