### ISSUE TITLE
TTS - Settings to not read emotes and links

### ISSUE THREAD

**Issue by rodrigograca31** [flex3r/DankChat#257]
I'd like to request 2 new options for TTS.

1. Dont read emotes out loud.... My viewers like to send emotes like :heart_eyes: :heart_eyes: :heart_eyes: and TTS will read it 3 times and it reads the emote text... which sometimes is "stupid" like "love2"  is read as "love two" ...
2. Dont read links...... Even tho I blocked the bots that posts links sometimes viewers (subs) post links to clips.... and its very anoying to hear `H T T P S colon slash slash.....`

**Comment by rodrigograca31** [comment]
btw, this is a feature request so I would apreciate if someone could tag it with `enhancement`

**Comment by rodrigograca31** [comment]
Ive just posted a bounty for this issue.
https://app.bountysource.com/issues/110740747-tts-settings-to-not-read-emotes-and-links

Whoever adds this feature will get 15$

**Comment by robmart** [comment]
Just took care of both issues at #309 check it out :)

**Comment by rodrigograca31** [comment]
we got 2 solutions!? oh boy.....

I think it will be up to @flex3r to analise which one is better/correct and merge it.

**Comment by silberkoenig** [comment]
Yep. What an unlucky timing. Didn't see this coming, sorry 😅

**Comment by robmart** [comment]
Oof, yeah that's unlucky. Oh well... :)
