### ISSUE TITLE
Option to hide time stamps and a amoled theme. 

### ISSUE THREAD

**Issue by Fatcakes** [flex3r/DankChat#27]
Please b0ss

**Comment by flex3r** [comment]
You can already hide timestamps, just open settings in the top right. By amoled theme you mean a completly black theme? I don't think I will add that, since the difference in energy consumption of a dark mode like dankchat currently has and a completly black theme is really small.

**Comment by Fatcakes** [comment]
The only option I see under format is the mentions format. I don't see a way to get rid of the time stamps.

The amoled theme imo just looks better though I may be in the minority on that. Thanks my dude.

**Comment by flex3r** [comment]
https://i.nuuls.com/qCaqX.png  This is how the Settings should look like on master. Google play has updated already, F-Droid always takes a bit longer to update, but the timestamp setting may be there already.
