### ISSUE TITLE
Keep stream open when using input

### ISSUE THREAD

**Issue by Blitszy** [flex3r/DankChat#271]
Whenever you use in-built stream function, it works flawlessly until you try to use the input box, once you do the stream disappears until you close input. Please fix so you can type while still viewing the stream, great app btw!

**Comment by flex3r** [comment]
Hey, this should be a visual-only workaround to ensure that the keyboard has enough space to actually open. The stream itself should keep playing in the background.
If I wouldn't hide the stream in this case, the keyboard would overlap with the chat, which is even worse in my opinion.
It's unfortunately a tradeoff but I haven't been able to find a better solution so far ;/

**Comment by Blitszy** [comment]
To be fair, you could try and program it like Twitch, when it detects you have opened the input box it will rise the chat and video so they're both still visible while you type, it does squeeze them down and won't give you as much space but it's a great solution to showing video and showcased by Twitch, it's a great workaround.

**Comment by flex3r** [comment]
I tried that but because I am forced to use a webview to show the embedded stream the actual video would be even smaller as it tries to keep the correct aspect ratio... But I will keep it in mind and see if I can come up with a better solution
