### ISSUE TITLE
Add first-time chatter highlights.

### ISSUE THREAD

**Issue by Foretack** [flex3r/DankChat#278]
On the 18th of October, 2021 Twitch introduced a highlight feature for first time chatters. Chat messages since have had the tag `first-msg=` added to them, to indicate whether this is a user's first message or not. 

Chatterino has implemented this feature a while ago, showing first messages with a dark-green background by default. It would be really nice if DankChat had something to highlight them as well.

**Comment by Foretack** [comment]
> is `first-msg=` sent to all connected clients or only the channel owner receives it? 🤔

This tag is a part of every message. So if your client can see the message, it can read that tag too

**Comment by rodrigograca31** [comment]
👍🏻👍🏻 I was just curious. 

Because in the browser chat we (the streamer) see "First message" but other normal chatters dont... but I guess technically speaking they could!

**Comment by zneix** [comment]
just for context, that fact that twitch announced the feature as being moderator/broadcaster only is completely flawed. I believe that I've even seen webchat show first time chatter despite not having moderator privileges in a chatroom; guessing they realized it's pointless to "gatekeep" it while their implementation made this information publicly available.
