### ISSUE TITLE
Enhancement: Temporarily disable custom mentions

### ISSUE THREAD

**Issue by PhotonGilbert** [flex3r/DankChat#285]
The new parameter can be next to  «Regex» and  «Match user» .

The «Temporarily disable» setting is needed in order not to remove the mention of «×», but to turn it off and on when the mention is needed again.

Why write a mention, and then delete and write it again, if you can temporarily disable it?

**Comment by flex3r** [comment]
I want to rework that list of mentions anyway to have seperate tabs for user mentions and message mentions. I agree that a checkbox to enable/disable an entry is super useful and will add that as well 👍
