### ISSUE TITLE
[Feature]  Tooltips of emotes

### ISSUE THREAD

**Issue by PhotonGilbert** [flex3r/DankChat#287]
A long click on an emote will open a card with information about the emote (emote name/ BTTV or FFZ or 7TV/ author).

This setting can be found in «Settings» → «Chat» → «General».

Maybe in the settings (Chat) you can create a separate section for emotions settings?

**Comment by flex3r** [comment]
Makes sense and is on my list of things I want to add for a long time now 👍

**Comment by M4tthewDE** [comment]
**Further refinement**
Short press might improve UX, since long pressing the message is already being used.

Included information:
- the emote
- the emote name
- what type of emote
- a button to copy
- a button to directly use it 
- who made the emote (for third party services)

**Comment by flex3r** [comment]
Rough estimation of 5
![image](https://user-images.githubusercontent.com/10165657/230378906-c1d82f68-fa2e-4fbe-93a6-ebb53c37b9b2.png)
