### ISSUE TITLE
Imgur configuration not working

### ISSUE THREAD

**Issue by deadclicks** [flex3r/DankChat#290]
### Bug Description:
Setting up Imgur in the "Configure uploader" option in DankChat settings (using this [guide](https://wiki.chatterino.com/Image%20Uploader/#imgurcom)) and then trying to upload an existing image results in: `Error during upload.. Retry`

<img src="https://i.imgur.com/Ne7tEx8.png" width="350"/>

### Things I tried:
- Updated to the latest available version of DankChat.
- Uninstalled the app and reinstalled again.
- Tried multiple Client IDs from Imgur.
- Using VPN.

Android Version: Android 12
DankChat Version: 3.2.4

**Comment by flex3r** [comment]
Fixed in 1ceddbfb0cefadad0c687508620c14af9bd0d6b5
