### ISSUE TITLE
Emotes not loading on startup

### ISSUE THREAD

**Issue by cineafx** [flex3r/DankChat#3]
One has to press `reload emotes` the first time the app starts from being fully shut off.

**Comment by flex3r** [comment]
Can you be more specific? Emotes load for me on startup, if the connection drops or has some other issues it fails of course, but emotes always loaded for me if the connection is stable.

**Comment by cineafx** [comment]
Okay this now it seems weird. Testing it yesterday evening the emotes never load when freshly starting the app.  
Now it works every time with no issues and I can't reproduce it at all.
![FeelsNotsureMan](https://user-images.githubusercontent.com/7873738/59177748-51141200-8b5d-11e9-813f-6b519d65c83c.png)
