### ISSUE TITLE
"XXX just mentioned you" notifications get triggered if the username is part of a word / emote

### ISSUE THREAD

**Issue by cineafx** [flex3r/DankChat#30]
`XXX just mentioned you in #YYY` notifications get triggered if the username is part of a word / emote.
`xxxxICDBxxxx` triggers for username `icdb`
![image](https://user-images.githubusercontent.com/7873738/63830972-c8439000-c96d-11e9-9ba2-053c9ecf0e82.png)

Something like this should work: `/\bUSERNAME\b/i`

**Comment by flex3r** [comment]
fixed in b4615986e9e5495e85ceb471278448c4a9980262
