### ISSUE TITLE
Enhancement: Interfering «Resume scroll» button

### ISSUE THREAD

**Issue by PhotonGilbert** [flex3r/DankChat#305]
If need to take a screenshot, then the cumbersome «Resume scroll» button interferes.

I suggest making the button disappear after 2 seconds after scrolling, or make it appear only after scrolling down the chat.

This button interferes only with me?

**Comment by flex3r** [comment]
I can hide it while scrolling is in progress, similar to how the chip at the top right is behaving right now. Would that work for you?

**Comment by flex3r** [comment]
Oh, I read your message wrong. No, automatically hiding the button after 2 seconds doesn't sound like good UX at all.
I know that some apps use the behavior you described in your 2nd suggestion but I have to think about that one first and play around with it.
