### ISSUE TITLE
Play Store update?

### ISSUE THREAD

**Issue by rodrigograca31** [flex3r/DankChat#306]
hi!

I noticed the app is on version `3.3` here on GitHub and F-Droid but the Play store one is at `3.1.13`
I've also noticed @flex3r seems to be the publisher/owner on the Play Store.

I do understand that life gets in the way and you got other things to do but that version is about 4 months old 😱

So I'd like to ask if there's any technical problem or it was just a lack of oversight? 🤔

**Comment by flex3r** [comment]
Hey, DankChat 3.3 is live on the Play Store via the open beta program. The Play Store has the largest audience by far so I like to test larger changes before pushing them to the production branch. 
So no, not a technical oversight. 
Feel free to join 🙂

**Comment by rodrigograca31** [comment]
Ok, fair.

I thought it was stable but even if it is I also put my apks on the beta track first 😂

Thanks for the clarification
