### ISSUE TITLE
Custom commands like supibot.

### ISSUE THREAD

**Issue by MrChuw** [flex3r/DankChat#328]
I have a twitch bot and would find it interesting if I could add my own commands to the dank. Having an interface similar to the mentions, where you would place the prefix and the command in each entry.

**Comment by flex3r** [comment]
That is already available under Settings->Chat->Custom commands. Let me know if the current implementation is lacking something.

**Comment by MrChuw** [comment]
it would be interesting to put the suggestions of the customized commands as well as supi

**Comment by jaimecy** [comment]
How are these commands used?  I have not seen a guide to see it, sorry.
