### ISSUE TITLE
Emotes not loading

### ISSUE THREAD

**Issue by wacra** [flex3r/DankChat#337]
![Screenshot_20221004-194852.png](https://user-images.githubusercontent.com/82950858/193890610-a67872d3-e391-44c2-861c-9b803f0dc541.png)

Only Twitch/Sub emotes work

Android 11, Pixel 4a, Newest Beta Appstore Version

**Comment by flex3r** [comment]
Looks to be a DNS issue. This could either be something on your side, for example via an AdBlocker that runs as a local VPN, on your internet provider, or a regional problem of the emote provider. 7TV had DNS related issues in the past.
Either way, this is not something on DankChat as we just consume the APIs like any other http client.
