### ISSUE TITLE
Change text «Confirmir block» for channel

### ISSUE THREAD

**Issue by PhotonGilbert** [flex3r/DankChat#341]
For deleting channels through the overflow menu has been added a new confirmation text: «Are you sure you want to remove channel "%1$s"? ».

For block through an overflow menu, could also add a new text: «Are you sure you want to block channel "%1$s"? ».

**Comment by flex3r** [comment]
@rod41732 another easy PR right here Keepo

**Comment by NewtonCesarRoncari** [comment]
Hello, i created a PR for this issue
