### ISSUE TITLE
[Bug] Incorrect clickable area for links at the end of the message

### ISSUE THREAD

**Issue by PhotonGilbert** [flex3r/DankChat#347]
### Problem
Clicking in the area after the link opens the link. Will not work if there is any symbol after the link. (check video)

### Expected Behavior
The clickable area must match the size of the link.

https://user-images.githubusercontent.com/108987349/195713201-7c4c4a26-d961-4238-bf22-e45c6c77b1e9.mp4

**Comment by flex3r** [comment]
This is a side-effect of an optimization I have enabled improve text rendering performance. For example, without [this flag](https://github.com/flex3r/DankChat/blob/master/app/src/main/res/layout-v23/chat_item.xml#L9) text rendering is causing major lags even on modern phones. I have noticed this on my own already but I think it's a worthy trade-off for the increased performance.
