### ISSUE TITLE
Enhancement: Update UX for scroll down button

### ISSUE THREAD

**Issue by PhotonGilbert** [flex3r/DankChat#348]
This was already mentioned in issue #305

Essence: Add behavior in which the scroll button appears only after scrolling the chat down.

Right Now: Scroll button appears when scrolling chat up and down.

**Comment by flex3r** [comment]
The scroll down button appears whenever you are not at the bottom of the chat and I don't really want to change that.  
For now the reduced size is a "good enough" change for me.
