### ISSUE TITLE
[bug] accepting username suggestions removes @ symbol

### ISSUE THREAD

**Issue by Mm2PL** [flex3r/DankChat#383]
The bug:
Using username completion will remove `@` prefix. This is particularly anger inducing with supibot which requires usage of `@`s.

How to reproduce:
  - type `@alaz` in your input box with pajs chat open
  - tap the suggestion
  - observe the input now reads `ALazyMeme`, not `@ALazyMeme`

**Comment by flex3r** [comment]
Fixed in b1732c0790ad91e5fa552fbf7ab02221514d64c4
