### ISSUE TITLE
Connection restarts around every 2 minutes while on vpn

### ISSUE THREAD

**Issue by AWildLink** [flex3r/DankChat#386]
I use nords app, while on mobile data the app works  consistently but when I switch to wifi with vpn it fisconnected-reconnected pretty much every other minute, other apps work just fine so I don't think my connection is unstable

**Comment by flex3r** [comment]
Twitch is known to block or at least not work very well with VPNs sadly. In your case it looks like Twitch is sending DankChat repeated "RECONNECT" commands which the app blindly exectutes..
In any case, I don't think there's anything I can do about this issue, sorry.
