### ISSUE TITLE
ffz supporter badges

### ISSUE THREAD

**Issue by francorz** [flex3r/DankChat#392]
that simple, ffz supporter aren't in the app and there's not viewers list or individual chatter logs, that two things are very useful

**Comment by flex3r** [comment]
That is intended actually, I do not plan on adding any supporter badges of 3rd party providers at the moment. In my opinion, this supporter badge should be in the 3rd party providers client, e.g. the web extension in the case of FFZ. I know that other clients like chatterino show these kind of badges so I might change my mind at some point. For now I'm going to close this one though.  
Also, there's an existing issue for the chatters list: https://github.com/flex3r/DankChat/issues/77 
If you want some way to show messages of a specific viewer, please create a separate issue for that.

**Comment by Enigmatic-Onion** [comment]
have you thought about adding them since this issue?

**Comment by flex3r** [comment]
It's not planned at the moment, especially since the project is in kind of a "maintenance" mode due to lack of time and interest for new features.
