### ISSUE TITLE
Avast scolds

### ISSUE THREAD

**Issue by vtuhes** [flex3r/DankChat#431]
Previously, every new version from the githab was fine. But the latest version is being scolded by the built-in Avast in MIUI.
p.s. translation of deppl

**Comment by flex3r** [comment]
Hi, you will have to provide some more details please. I don't have a phone with MIUI myself. I can however 100% gurantee that this is a false positive.

**Comment by vtuhes** [comment]
I'm sorry, I don't know what I can give you. That it's a false positive is clear enough. I just wanted to let you know.

**Comment by flex3r** [comment]
Can you share some screenshots? What exactly is Avast detecting DankChat as? Any additional information would help.
If possible I will try to file a false positive claim

**Comment by vtuhes** [comment]
Sorry. I wanted to take a screenshot (even though it's in a different language). But firefox won't even let me download the apk file right now, and chrome won't let me install it. This started after 3.5.15. Now I use the version from Google Play, thankfully you recently updated it there.
p.s. deepl

**Comment by flex3r** [comment]
Very strange, virus total is showing 0 detections: https://www.virustotal.com/gui/file/56f111c20abb47007d4e89ac587232044ce86471bb47ac43ce5ac319bd191b6a/detection
Still, thank you for the report. I will keep this in mind

**Comment by vtuhes** [comment]
![Screenshot_2023-03-24-22-41-17-785_com android vending](https://user-images.githubusercontent.com/100627060/227590415-4a71a6b9-7745-44c2-9dff-4b756a4c415a.jpg)
Now allows download apk file. But the playmarket swears "Could not find developer information".

Google Translate

**Comment by flex3r** [comment]
I guess that is to be expected since it is just a debug build. I'm going to close this for now but feel free to re-open it if you have any news.
