### ISSUE TITLE
FFZ emotes not working

### ISSUE THREAD

**Issue by Sileniful** [flex3r/DankChat#444]
For around a week or two i noticed that FFZ emotes aren't being displayed properly, while you can pick them from emote menu and autocomplete, in emote menu pic shows as loading and in chat it shows as plain text, the FFZ emotes are displayed just fine on native twitch with FFZ extension and on chatty. I'm on version 3.5.18. Tested the issue in both channels visible on screenshot.
![Screenshot_2023-03-05-13-09-40-090_com flxrs dankchat](https://user-images.githubusercontent.com/1914729/222959936-6524f565-9f65-48c1-846b-3dc14420d273.jpg)

**Comment by Felanbird** [comment]
> the FFZ emotes are displayed just fine on native twitch with FFZ extension and on chatty

I assume you aren't using DankChat on your computer? So the fact that desktop applications work should be unrelated to your phone

**Comment by Sileniful** [comment]
chatterino has this issue as well but i don't use it typically, in fact i just downloaded it to test
![image](https://user-images.githubusercontent.com/1914729/222982115-75e1496f-c40f-41f0-969c-60ad4f45c0dd.png)

also i ended up reinstalling the app with latest update now, reloaded and emotes work

**Comment by Felanbird** [comment]
>chatterino has this issue as well but i don't use it typically, in fact i just downloaded it to test

**Comment by Felanbird** [comment]
but if it's fixed now then 👍

**Comment by flex3r** [comment]
As @Felanbird already mentioned the issue seen in your screenshot has already been fixed. Not sure what issue you have been having for "weeks" but I have not noticed anything my self. If there is still an issue please create a new issue with proper details.
