### ISSUE TITLE
White "logged in" box in dark mode

### ISSUE THREAD

**Issue by TranRed** [flex3r/DankChat#45]
This  box was also dark themed before the last update feels like a bug.

![Screenshot_20200214-092846](https://user-images.githubusercontent.com/16636423/74514513-00835e80-4f0d-11ea-8493-a985f2811671.jpg)

**Comment by flex3r** [comment]
This is intentional and complies with the android material guidelines, see "Combining light and dark themes" https://material.io/design/color/dark-theme.html#custom-application for further details.
