### ISSUE TITLE
star for people who subbed to my twitch

### ISSUE THREAD

**Issue by ELY3M** [flex3r/DankChat#46]
I noticed that it is missing in dankchat.      
I see stars next to the usernames in the twitch client.

**Comment by flex3r** [comment]
Hey, I joined your channel to test it out myself and could see the stars next to subscribers. Are you on the latest version? You can check your version at the bottom of the settings screen.

**Comment by ELY3M** [comment]
Thank you for pointing out about the version.  I am on 1.6.3  I will update it right now.  
is there a way to whisper people in same app?    what is command for whisper people?

**Comment by flex3r** [comment]
There is basic whisper support, receiving whispers get displayed as normal chat messages with an additional whisper indicator. If you want to write a whisper you currently have to use the command syntax (\w USERNAME MESSAGE). I will definitely add a better support in the future though
