### ISSUE TITLE
Use external player option for the stream.

### ISSUE THREAD

**Issue by Toiletmason** [flex3r/DankChat#461]
Would be nice to be able to open the stream with a different player. Samsung's built-in player is pretty good honestly and it's nice to use its pop out player.

**Comment by flex3r** [comment]
Unfortunately Twitch forces third party clients to use their embedded web viewer as the only allowed way to show streams. But the popout player could still be possible and it's something I wanted to investigate.

**Comment by vtuhes** [comment]
very lacking background playback

**Comment by Toiletmason** [comment]
@flex3r I'm not one to question you cause you know way more about this stuff than me, but how does Twire achieve this? https://github.com/twireapp/Twire

**Comment by flex3r** [comment]
I'm not saying it's not possible to do this, it's just against the developer agreement of Twitch to do this. Apps have been banned from the PlayStore in the past for it and I am not willing to risk that.

**Comment by Toiletmason** [comment]
@flex3r that makes sense. Twire isn't on the playstore.

**Comment by flex3r** [comment]
Experimental picture-in-picture support has been added with https://github.com/flex3r/DankChat/pull/631

**Comment by vtuhes** [comment]
> Добавлена ​​экспериментальная поддержка «картинка в картинке» с [номером #631.](https://github.com/flex3r/DankChat/pull/631)

Kreygasm If only it would continue to work on the locked screen and I would forget about all the other Twitch applications
