### ISSUE TITLE
Blocking a message with ignored words doesn't function, at least with sentences having Chinese Traditional(zh-TW) characters.

### ISSUE THREAD

**Issue by him157** [flex3r/DankChat#465]
As the title says I have the user's user name blocked in ignore as shown below : 
![Screenshot_20230401_091041](https://user-images.githubusercontent.com/47471963/229258491-e9d2fb8e-e9fa-4c95-b072-1d62427ec036.jpg)
![Screenshot_20230401_091213](https://user-images.githubusercontent.com/47471963/229258497-4a77338d-4ff0-4a51-909a-37e974c6a454.jpg)

But replacing the words does work, showing that DankChat did found the word as pictures below would suggest : 
![Screenshot_20230401_091512](https://user-images.githubusercontent.com/47471963/229258629-4928f5d3-474b-4ea0-b5c5-7e89868b65a8.jpg)
![Screenshot_20230401_091452](https://user-images.githubusercontent.com/47471963/229258655-1c86d82b-7668-475c-84e5-f330d93da2a2.jpg)

Additionally, DankChat can also find Chinese Traditional characters just fine, and replacing them as shown below : 
![Screenshot_20230401_092226](https://user-images.githubusercontent.com/47471963/229259038-61408285-3e08-4d24-9d1f-f3f7045526be.jpg)
![Screenshot_20230401_092030](https://user-images.githubusercontent.com/47471963/229259046-7ef62dec-e3fe-4b03-83a1-ebe83b01d759.jpg)

After turning off block : 
![Screenshot_20230401_092154](https://user-images.githubusercontent.com/47471963/229259072-619e6676-5fa3-4bf2-8afc-3fd421b90b03.jpg)
![Screenshot_20230401_092132](https://user-images.githubusercontent.com/47471963/229259081-e24c7923-301f-4354-a3c8-75f7a2c04b27.jpg)

**Comment by flex3r** [comment]
Looks like I broke the block flag in general, not just with chinese characters in a recent commit (067c3bdf)
