### ISSUE TITLE
reading emotes & ignore word

### ISSUE THREAD

**Issue by AUTdany** [flex3r/DankChat#467]
The app reading emotes even you set the setting ignore emotes if a user only text one emote...

and i cant ignore that "^"

android 13
pixel 5

**Comment by flex3r** [comment]
Hm, when I enable the ignore emotes setting messages are not read out if a user only sends one emote. Perhaps I don't quite understand your issue, could you explain it in more detail?

**Comment by AUTdany** [comment]
![image](https://user-images.githubusercontent.com/128122660/230742872-8adc32c4-01a4-4343-a5dc-efde3be158a9.png)

if someone write only one emote it will be reading by tts... if someone wrtie more than one emote tts doesnt read it out

**Comment by flex3r** [comment]
Yeah, I cannot reproduce this unfortunately. For me the ignore emotes setting works as expected, no message is read out with either one emote or many..
Does this happen with a specific type of emote, e.g. a Twitch or 3rd party one? Any additional information would help me reproduce this issue.

**Comment by AUTdany** [comment]
all emotes dosent matter wich one.. all of my emotes , if they user wrtie only one emote, that emote will read out by tts

i deinstal the app.. delte the cach and storage.. nothing help... the app will read out the emote if a viewer only post one

**Comment by AUTdany** [comment]
so i did it again.. clear the cach and delte the storage.. NOW its working.. thanks for help sir <3

**Comment by flex3r** [comment]
Nice that you were able to fix it! Closing this issue :)
