### ISSUE TITLE
How to get sub emotes?

### ISSUE THREAD

**Issue by ShowTsai** [flex3r/DankChat#475]
As the title, I wonder how to get all the sub emotes of the logged-in user.
Thanks.

**Comment by flex3r** [comment]
Can you clarify what you mean by "all the sub emotes"? If you are logged in the emote menu should show all emotes available to that user.

**Comment by ShowTsai** [comment]
I mean how to get all the emotes that the logged-in user can use including sub emotes and cheer emotes.
I wonder which twitch apis can be used to get these informations.
Thanks.

**Comment by flex3r** [comment]
The only way to get the emote-sets available to a user at the moment is via the `USERSTATE` irc message: https://dev.twitch.tv/docs/irc/tags/#userstate-tags
The sets that are returned by this tag can then be queried via https://dev.twitch.tv/docs/api/reference/#get-emote-sets, for example.  

Also, as a side not, please don't use this repository for general questions about Twitch. There is an official discord for that:
https://discord.com/invite/G8UQqNy
