### ISSUE TITLE
Missing follower information in user popup

### ISSUE THREAD

**Issue by jaimecy** [flex3r/DankChat#488]
Hello.  Before, when clicking on a nick, the creation date would appear and since when I was following a channel, now in the beta only the creation date appears, I would like both dates to appear.  Greetings.

**Comment by flex3r** [comment]
This is an intended change which is also described in the latest changelog:
Essentially Twitch is restricting access to this kind of follower information to Broadcasters or Moderators of the respective channel and there's not much more I can do about it.   
More information can be found here: https://discuss.dev.twitch.tv/t/follows-endpoints-and-eventsub-subscription-type-are-now-available-in-open-beta/43322#why-make-this-change-1
