### ISSUE TITLE
Option to rename tabs

### ISSUE THREAD

**Issue by cineafx** [flex3r/DankChat#5]
This would allow for shorter names.  
E.g. rename pajlada to paj and forsen to fors 

May in some *hold* option together with #4 ?

**Comment by flex3r** [comment]
Renaming should be possible, I can't do it by holding a tab though since the current layout setup isn't providing a callback/listener like that.  An option in the option menu is a possibility though.

**Comment by diego411** [comment]
@flex3r I'd like to give this a try if that's ok

**Comment by flex3r** [comment]
Sure, go for it!
