### ISSUE TITLE
Chat moderation problem

### ISSUE THREAD

**Issue by jaimecy** [flex3r/DankChat#503]
Hello.  I'm in the latest beta version, I don't know if this worked well in others: in my chat, being the owner of my channel, I can't ban a user from the app, I can only set subscribers, followers mode... Is this it's a mistake?  Greetings again and thanks.
![Screenshot_20230508-202702_DankChat_1](https://user-images.githubusercontent.com/4126584/236904322-aaecf847-a8a5-4440-920a-bd153b2556bf.jpg)

**Comment by flex3r** [comment]
Hi, the moderation actions have moved from the user popup to the new message popup, as mentioned in the changelog. I guess I should have made this change a bit more clear, I apologize. You can open this new popup by long pressing anywhere on a message.

**Comment by jaimecy** [comment]
![Captura de pantalla 2023-05-12 210139](https://github.com/flex3r/DankChat/assets/4126584/d1742046-1794-4ace-9f3b-92072fa3802c)
Now with the new beta, 3.6.29, I do get everything to moderate. Thank you!!
