### ISSUE TITLE
Add new twitch emotes from 2021

### ISSUE THREAD

**Issue by rodrigograca31** [flex3r/DankChat#515]
Hi!

Been loving the new beta with the reply threads and everything! thanks!

Just wanted to note that the app still doesnt display [the new Twitch Emotes from 2021](https://blog.twitch.tv/en/2021/11/01/animal-week-is-very-good-yes-it-is/)

Like `:HypeSleep:` 
![image](https://github.com/flex3r/DankChat/assets/1134310/3588bba1-1101-44f4-a007-05d871b20096)

Maybe its because its one of the hype train unlockable emotes?
Is there a way that could be implemented in the future or not really?

Thanks

**Comment by flex3r** [comment]
Hi, are you talking about the emote not showing up in the emote menu?
If yes - Unfortunately Twitch does not provide a good solution for third parties to query all available emotes of an user. This is why some of the emotes might be missing in the menu compared to the first party app or website. 
The most common emotes that are missing are some of the unlockable emotes that Twitch added, like hype train emotes. 
So unless Twitch adds a better way for third party developers (which we have asked for many times), there's nothing I can do unfortunately :/

**Comment by rodrigograca31** [comment]
That sucks... :cry: 
Ok then I guess I will close the issue.
Thanks tho!

**Comment by rodrigograca31** [comment]
I am back.... :D

I found this website which can actually tell which emotes the user has access too!
https://sikorsky.rosuav.com/checklist

Don ask me how they do it tho... But I saw a call to a websocket...
their code seems to be open source tho!
https://github.com/rosuav/stillebot

[searching the repo for `checklist` gives us some useful code!](https://github.com/search?q=repo%3ARosuav%2FStilleBot%20checklist&type=code)

Their output seems to be correct for me!
![image](https://github.com/flex3r/DankChat/assets/1134310/946bee2e-296b-46b7-9438-f84de4596a56)
