### ISSUE TITLE
recent-messages optin system

### ISSUE THREAD

**Issue by RAnders00** [flex3r/DankChat#52]
For legal reasons, you should have your users explicitly opt in to using the recent messages service (on first startup or something).

Tell the user:
- that DankChat will fetch messages from the recent_messages service
- it will send each channel name you visit to a third-party service for that,
- and that channels you visit will have their messages stored
- that you can opt out of having the bot collect messages in your own channel by using the bot/system at https://www.twitch.tv/recent_messages (Info about optout procedure can be found on that page, in the panels)
- and with a link to the privacy statement (https://recent-messages.robotty.de/privacy)

**Comment by flex3r** [comment]
I added a dialog that will show up on first startup in commit 79540552904f620dac91565a5e53b23cf8bad5ac, it currently looks like this: https://i.nuuls.com/n-oWV.png. I also added a setting to disable message history loading.  
Let me know if you want any more changes

**Comment by flex3r** [comment]
Final disclaimer text added in 1d799af4725917354f6324e04650989ac5bd66da
