### ISSUE TITLE
No badges

### ISSUE THREAD

**Issue by Mad5tyl3** [flex3r/DankChat#530]
Hy.. Im Support you since 1 month edit my profile with 7tv badge and lemon slice color butb i dont see it on dankchat or at chat from Montanablack.. Other users have them too, i see them badge and color name..
Im on Android phone, any ideas?
Thx Mad5tyl3

**Comment by Mad5tyl3** [comment]
I think its done

**Comment by flex3r** [comment]
Hi, 7tv badges and paints are not supported in DankChat and there is currently no planned support for it in the near future.
My main reasoning is the unknown effort to implement the paints and that it is a mostly payed feature that I don't like to be visible in a third party client.
Also feel free to state your question in German if I misunderstood your issue.
