### ISSUE TITLE
Update some dependencies

### ISSUE THREAD

**Issue by TacoTheDank** [flex3r/DankChat#56]
The [safe-args plugin](https://github.com/flex3r/DankChat/blob/master/build.gradle#L10) is pretty behind; it's not even using the AndroidX version.
https://developer.android.com/jetpack/androidx/releases/navigation
https://mvnrepository.com/artifact/android.arch.navigation/navigation-safe-args-gradle-plugin
https://mvnrepository.com/artifact/androidx.navigation/navigation-safe-args-gradle-plugin

Koin has many a version since 2.0.1! Here's the [changelog](https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md), be wary of any new features you'd like to implement, as well as breakages.

Coil has 0.11.0 now. Here's the [releases](https://github.com/coil-kt/coil/releases). As above, check for anything you'd like to implement, as well as breakages.

(Sorry for this. Goddamn I'm so weird.)

**Comment by flex3r** [comment]
I think the safe-args isn't even used anywhere in the project, so I should really remove it.  
I had updated to coil 0.10 when it first came out, but had some weird issues/crashes on some devices with the underlying okhttp client and cache changes. I'll have to look into that first before updating.  
Koin looks good though!
