### ISSUE TITLE
Suggestion: Horizontal chat input field scrolling

### ISSUE THREAD

**Issue by deadclicks** [flex3r/DankChat#565]
A suggestion to change the way the chat input field behaves:

Currently, the input field scrolls _horizontally_ when the text exceeds the field size, making it expand _vertically_ would make it much easier to read the full text entered before sending.

Example image:

![](https://i.imgur.com/bKqW2Pe.png)

**Comment by SputNikPlop** [comment]
@flex3r Is this something you would like to implement if so I would be happy to take some time to fix this

**Comment by flex3r** [comment]
@SputNikPlop Sure, go for it!
