### ISSUE TITLE
Add channel example to prompt (maybe in form of question mark icon)

### ISSUE THREAD

**Issue by TacoTheDank** [flex3r/DankChat#57]
To help people that may not know what to actually put in the "Add channel" box. Like, put a question mark on the far right of the prompt box, and when you click on it, it tells you what to actually put in the box, which is the name of the Twitch channel itself, not the whole https link or whatever else people might try to put in it. Also maybe change "channel" to "channel name" in the textbox. Thanks!

That probably wasn't clear. I'll edit a screenshot just in case. Something like this.

![dope question mark thing](https://user-images.githubusercontent.com/32376686/82625110-4f96fa80-9bb2-11ea-943d-116d5679b315.png)

(Also, you should maybe shorten the line length and add some padding to the left of "Channel" so it aligns more with "Add channel". It'll make it look a bit nicer.)

**Comment by flex3r** [comment]
Hm, not sure about the layout changes, I use the material design version of the alert dialog and it complies to the material guidelines, so manually changing e.g. padding seems wrong. I'll think about the question mark idea but not too sure how I feel about that either. Updating the hint is a good idea though, thanks!
