### ISSUE TITLE
Follow date information of a user in a channel

### ISSUE THREAD

**Issue by jaimecy** [flex3r/DankChat#575]
Months ago, this information about the start date of following a user on a channel appeared on DankChat. You supposedly removed it because Twitch was going to remove it, and this information is still out there in the Twitch chat and also with 7tv.

Are you going to re-enter this information? I hope so, greetings and thanks.

![Captura de pantalla 2023-08-31 154409](https://github.com/flex3r/DankChat/assets/4126584/c09b18ea-fba7-49d4-b3ff-3ebbe4ef640e)

![Captura de pantalla 2023-08-31 153622](https://github.com/flex3r/DankChat/assets/4126584/3b825375-771c-45a5-a22d-100524c67cb9)

![Captura de pantalla 2023-08-31 154657](https://github.com/flex3r/DankChat/assets/4126584/977f56b0-8554-440f-ad63-6d7f3bd8f40f)

**Comment by flex3r** [comment]
Hi, Twitch is removing access to this information by third parties unfortunately. More information can be read here:
https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769

**Comment by jaimecy** [comment]
And why do Twitch itself or 7TV have that information?
