### ISSUE TITLE
Click on username and display user information

### ISSUE THREAD

**Issue by ajdelcimmuto** [flex3r/DankChat#6]
Some information may include:
- Date created
- Profile picture
- views and followers count

**Comment by flex3r** [comment]
Currently, the name get's copied into the input field when clicked for quickly mentioning someone. Would you move that feature into the popup that opens on click too? Or do you have some other idea how that feature could be handled..

**Comment by ImVerbatim** [comment]
After thinking, I feel tapping a name is better for mentions. However, maybe an OnLongClickListener that can bring up a user information popup. I am going to experiment with this enhancement in my own fork to see what it may be like.

**Comment by defvs** [comment]
@flex3r if you're not currently working on that I'd like to implement a dialog (popup) to show details about an user, its profile pic, and maybe even have a note field per user.

**Comment by flex3r** [comment]
Sure, go for it 👍 
Some things that came to my mind:
- The mention function should also be in the dialog, since it will be replaced by the dialog
- A bottomsheet dialog should preferably be used, like the custom mentions dialog in the settings
- Maybe moderation actions can be added to the dialog if the user is a moderator in the channel? That's probably a thing for the future though

**Comment by defvs** [comment]
@flex3r was implementing a bottomsheet indeed. Sound better.
I wanted to show the dialog on username long click but it's not feasable with the current implementation of ClickableSpan. We could do it on message long click instead, make the dialog more of a "message info" but still with user info, copy message button, mention, note field, moderation...

**Comment by flex3r** [comment]
Yeah, I like that 👍

**Comment by defvs** [comment]
Kinda like that ?
![image](https://user-images.githubusercontent.com/19249728/90257959-26e86f00-de48-11ea-8b84-d5025bc38bc1.png)

Thing is on tablet this is going to look pretty bad. Might be worth doing a different layout for larger sizes.

**Comment by flex3r** [comment]
- I'm not sure about the note field, what's the usecase behind that? That area could be used for moderation 
- What would the "message" fields display? Logs of the user?  
 
> Thing is on tablet this is going to look pretty bad. Might be worth doing a different layout for larger sizes.

Yeah, I haven't given tablets any thought. I'm sure other layout choices look pretty bad on tablets already, imo that's a future improvement

**Comment by defvs** [comment]
For context I was devving my own twitch chat app for a friend who streams (I also do stream!) and wanted some more features. For small communities having a note field to put user info is nice addition. he requested me to ass this feature.
if you don't feel like adding a note field no big deal I'll make it on my fork and you'll see then

**Comment by flex3r** [comment]
Hm, yeah I'm still not sure about it.. Maybe we can leave it out for now and make it a separate issue?
It just opens a couple more questions, like how are these notes saved? Would it require a local database?

What I think could work is making it optional, like a checkbox in the dialog which would, only when activated, show the note field...

**Comment by defvs** [comment]
Sorry for making this issue stale. Not interested in continuing dev. Good luck going forward.
