### ISSUE TITLE
Some emotes bugged 

### ISSUE THREAD

**Issue by francorz** [flex3r/DankChat#620]
idk if it's something that is happening to other people, but I used to see this in emotes:

![SmartSelect_20231027-181937_DankChat](https://github.com/flex3r/DankChat/assets/83022459/773378f9-eedb-46b2-9508-efd51107b2a2)
![SmartSelect_20231027-181951_DankChat](https://github.com/flex3r/DankChat/assets/83022459/9ada7727-6a71-4e2f-b108-ece83e67afba)

As you can see, the emote have a weird name. The actual name is ["ryanpo1KEK"](https://emotes.raccatta.cc/twitch/emote/emotesv2_3d333a49d1eb41c3a7a8df363171a2c2). it's not happening only with this emote, happens to other ones sometimes.

**Comment by flex3r** [comment]
Interesting, could be related to some of the emojies that are included in the message. If you encouter this bug again, can you copy and share the message here? You can do that by long pressing the message.

**Comment by francorz** [comment]
just happened again with this message:
03:32 PotatBotat PogChamp キ 󠀀 ャン 󠀀 ドル 󠀀 セン was distracted, and you took advantage of the opportunity to steal some potatoes [+482 ⇒ 22,812] ⏰ 1h and 26m

![lol](https://kappa.lol/AC-Mk)

![lol](https://kappa.lol/io09h)
