### ISSUE TITLE
Android accessibility Text-To-Speech for messages

### ISSUE THREAD

**Issue by cineafx** [flex3r/DankChat#65]
Pretty much also allow to play tts messages while the phone is locked / a different app is in the forground.

I have little to no experience (and this post is extremely old) but it seems rather straight forward: https://android-developers.googleblog.com/2009/09/introduction-to-text-to-speech-in.html

Yeah a bunch of stuff changed but overall the same principle still applies [.say](https://developer.android.com/reference/android/speech/tts/TextToSpeech#speak(java.lang.CharSequence,%20int,%20android.os.Bundle,%20java.lang.String))

**Comment by flex3r** [comment]
Added basic functionallity for it in 4d483d62bd598b0604f094c3d726b30f9950fad6, for now under developer options

**Comment by MrJaroslavik** [comment]
Not sure if i should create new issue, but it would be good add possibility to change TTS language, for example i would appreciate Czech TTS.

**Comment by flex3r** [comment]
Yes please create a new issue, right now it is a pretty simple implementation which is also the reason why it's under dev settings. Support for languages will be a bit more effort.
