### ISSUE TITLE
Dankchat unfollowed a long time streamer of mine

### ISSUE THREAD

**Issue by lunarwinds84** [flex3r/DankChat#697]
I had years of following for a streamer and when I logged into dankchat on a new phone it apparently unfollowed the streamer. This is very maddening.....!!!!!!

**Comment by flex3r** [comment]
No, DankChat did not randomly unfollow your streamer. There isn't even support for following/unfollowing in DankChat and Twitch even removed the ability for third party clients to follow/unfollow almost 3 years ago.
