### ISSUE TITLE
Buttons for "delete message" and "timeout" missing

### ISSUE THREAD

**Issue by Deavez** [flex3r/DankChat#754]
Hello!

I'm having problems with the buttons when tapping on a username.

I don't have any buttons there to delete messages or timeout like in the preview in playstore

I am using android and the latest version from the store.
![image](https://github.com/user-attachments/assets/54f81b85-392c-4da2-8d35-f3b370d29fc1)

**Comment by flex3r** [comment]
Moderation actions have moved to long pressing the message instead of the user a while ago. When I did that update I forgot to properly communicate it, for example via a changelog or hint. Sorry about that.
