### ISSUE TITLE
Add option to integrated notification from streamlabs etc

### ISSUE THREAD

**Issue by Damianuscz** [flex3r/DankChat#82]
Thx for great software then i and other irl streamers use for comunication with chat. There is other ways to see chat but no one have feature to integrate sound alerts from streamlabs or audiohooks from phantombot etc..

I thinkg many irl streamers seek the way how to have chat, alerts, audiohooks, music on one device.

**Comment by flex3r** [comment]
I understand the interest but I think I want to keep the app focused on Twitch right now. 
I might pick up other integrations when I'm happy with the features for Twitch, but I will close this for now.
