### ISSUE TITLE
Dark mode for notification

### ISSUE THREAD

**Issue by Daisenki** [flex3r/DankChat#83]
Unfortunately the dark mode does not work at the notification, it's a endless fight because apps need to support the dark notification otherwise you have white and dark notifications with a dark theme.

Maybe you could add this to the dark mode of the app or as separate setting. 

The notification is better minimized, it's basically the same but needs less space, but when you minimize the notification the icon in the bar is gone. Is there a way to change that? My personal preference would be:
Minimized dark notification with icon
Maybe it's possible to separate the icon and the notification, to have only the icon or only the notification

**Comment by flex3r** [comment]
I'm not sure what you mean with dark notification to be honest, I've never heard about a way to adjust the actual theme of the notification. On my phone the notification is colored according to the OS dark/light mode setting.  
I'm also not able to seperate the icon and the foreground notification, but I will try to make the notification collapsible.

**Comment by Daisenki** [comment]
My V30 runs Android 9 and the notifications only changes the colors if the app supports that. DankChat runs at dark mode but the notification is still white, so I guess it's not supported. I don't know how it is with other phones or newer Android versions, I can install dark themes, but the are not interact with app notifications. 
The weather app Chronus supports a dark notification in the settings, I can change the color of the notification.

![Uploading Screenshot_20200915-114531.png…]()

**Comment by flex3r** [comment]
I looked at the documentation and best practices again, I use recommended notification templates that make sure that the system is responsible for styling the notification. It seems like your OS doesn't support dark notifications by default.  
The way the weather notification (and other apps) circumvent this is by adding a completely custom notification view, which I won't do. I want to make sure to stick to recommended best practices.  

Also, since the sticky notification is an indicator that the app is running as a foreground service, it can't be minimized by the app itself. 
You should be able to silent it yourself though.

**Comment by Daisenki** [comment]
Hm ok, in that case I guess I deactivate the notification. Is there a way to only get the icon in the bar when the app is running, foreground and background? I When I deactivate the notification the icon is also gone with the current available settings. If nothing works I deal with the deactivated stuff for the design till I get a new smartphone with newer Android.

**Comment by flex3r** [comment]
No, sadly I don't think I can do that. The icon is part of the notification :/  
I'm going to close this for now but I'll keep looking for a good solution to fix the notification theming issue that won't require creating a custom design.

**Comment by Daisenki** [comment]
Forget about it, I found the "problem", the theme app in the Playstore is modified because of Googles policies, it doesn't have all the features, complete weird, you need to buy the app in the Playstore and then install the previous version that you get from the developer. It includes the dark notifications.

![Screenshot_20200915-213049(1)(1)](https://user-images.githubusercontent.com/22057956/93256551-c8424800-f79b-11ea-83cd-0e040a14d629.png)
