### ISSUE TITLE
2.2.3 force close at back

### ISSUE THREAD

**Issue by Daisenki** [flex3r/DankChat#84]
The version 2.2.3 close complete every time when I go back, using the back button in the navigation bar, it was not the same in the previous version.
I pin the open app, did battery saving exception, allow all, but the app still force closes.
Idk if it is a bug or you chance something, but it's weird and shouldn't be like that. I can't close the keyboard or emote menu because it closes the complete app. Going in the settings and go back does not work with navigation bar back too.

**Comment by flex3r** [comment]
Yeah this was a bug, fixed in 26a3ee577603ee17188699deee695a6e933b5b32

**Comment by Daisenki** [comment]
Thanks for fixing
